### ISSUE TITLE
Create sample `test.db` with small map

### ISSUE THREAD

**Issue by zonca** [simonsobs/tilemaker#4]
For testing purposes, instead of using a 5 GB map from ACT (for which I don't have space on my laptop disk btw), it would be great to create a simple map at low resolution.

The plan is to create a `test.db` so small that can be added to the repo and used in Github Actions for testing.

@JBorrow let me know if you have any feedback, otherwise I'll give it a try and report back here.
@jernestmyers once I have this working you can also test the frontend with this.

**Comment by JBorrow** [comment]
Hey Andrea, I think that there is already a script that does this in examples. I'd much prefer to have the script to do it than the database itself.

**Comment by zonca** [comment]
Yes, that is what I meant, I want to try and check if that script works on
a simple map I create

**Comment by JBorrow** [comment]
Sorry, I meant `simple.py` which creates a very simple noise-filled map for testing purposes.

Cheers,
Josh

**Comment by zonca** [comment]
`simple.py` in the example folder works fine,
it creates a database of 22 MB that can be used for testing.

**Comment by zonca** [comment]
@jernestmyers if you haven't already, it would be useful to test your frontend with it.

**Comment by JBorrow** [comment]
Great!
